apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector: # this links the nodeport to a pod (matches labels)
    app: myapp
    type: back-end